site_name: Lefi
site_author: an-dyy
site_description: A discord API wrapper focused on clean code, and usability

theme:
  features:
    - search.highlight
    - search.sharing
    - navigation.top
    - navigation.tabs

  name: material
  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"

      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting-Started: getting-started.md
  - API-Reference:
    - Client: API-Reference/client.md
    - HTTPClient: API-Reference/http.md
    - WebSocketClient: API-Reference/wsclient.md

    - State: API-Reference/state.md
    - Channel: API-Reference/channel.md
    - TextChannel: API-Reference/textchannel.md
    - VoiceChannel: API-Reference/voicechannel.md
    - DMChannel: API-Reference/dmchannel.md

    - Cache: API-Reference/cache.md
    - Errors: API-Reference/errors.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            members_order: source
          import:
            - https://docs.python.org/3.9/objects.inv
            - https://docs.aiohttp.org/en/stable/objects.inv

repo_name: an-dyy/Lefi
repo_url: https://github.com/an-dyy/Lefi

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
