site_name: Lefi
site_author: an-dyy
site_description: A discord API wrapper focused on clean code, and usability
repo_name: an-dyy/Lefi
repo_url: https://github.com/an-dyy/Lefi

extra_css:
  - stylesheets/extra.css

theme:
  features:
    - search.highlight
    - search.sharing
    - navigation.top
    - navigation.tabs

  name: material
  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"

      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting-Started: getting-started.md
  - API-Reference:
    - Extensions:
      - Bot: API-Reference/exts/commands/bot.md
      - core:
        - API-Reference/exts/commands/core/parser.md
        - API-Reference/exts/commands/core/command.md
        - API-Reference/exts/commands/core/context.md
        - API-Reference/exts/commands/core/cooldown.md
        - API-Reference/exts/commands/core/handler.md
        - API-Reference/exts/commands/core/plugin.md

    - Interactions:
      - Interaction: API-Reference/interactions.md

    - Components:
      - Button: - API-Reference/button.md
      - SelectMenu: - API-Reference/selectmenu.md
      - Option: - API-Reference/option.md
      - ActionRow: - API-Reference/actionrow.md

    - Client: API-Reference/client.md
    - HTTPClient: API-Reference/http.md
    - State: API-Reference/state.md
    - Channel: API-Reference/channel.md
    - Guild: API-Reference/guild.md
    - Member: API-Reference/member.md
    - User: API-Reference/user.md
    - Message: API-Reference/message.md
    - Overwrite: API-Reference/overwrite.md
    - Role: API-Reference/role.md
    - Embed: API-Reference/embed.md
    - Cache: API-Reference/cache.md
    - Errors: API-Reference/errors.md
    - Emoji: API-Reference/emoji.md
    - Integration: API-Reference/integration.md
    - Invite: API-Reference/invite.md
    - Template: API-Reference/template.md
    - BanEntry: API-Reference/banentry.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            members_order: source
          import:
            - https://docs.python.org/3.9/objects.inv
            - https://docs.aiohttp.org/en/stable/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
